name: ESLint Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Specify your Node.js version here

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn run lint --config eslint.config.mjs

      - name: Upload ESLint results as artifact (optional)
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: eslint-report
          path: .eslintcache
